#Configurar puerto
server:
    port: 8032


# Configuración de la base de datos
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Franquicia
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
  
  jackson:
    time-zone: "America/Bogota"
    
feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
        loggerLevel: basic
